from typing import Any, Callable, Optional
from types import TracebackType

# Re-export everything that is directly imported (not wrapped)
from .icedpygui import (
    add_button_style as add_button_style,
    add_checkbox_style as add_checkbox_style,
    add_container_style as add_container_style,
    add_divider_style as add_divider_style,
    add_pick_list_style as add_pick_list_style,
    add_radio_style as add_radio_style,
    add_scrollable_style as add_scrollable_style,
    add_scroller_param as add_scroller_param,
    add_autoscroll_style as add_autoscroll_style,
    add_rail_style as add_rail_style,
    add_separator_style as add_separator_style,
    add_slider_style as add_slider_style,
    add_text_input_style as add_text_input_style,
    add_toggler_style as add_toggler_style,
    Align as Align,
    AlignX as AlignX,
    AlignY as AlignY,
    IpgArrow as IpgArrow,
    IpgButtonParam as IpgButtonParam,
    IpgButtonStyleParam as IpgButtonStyleParam,
    IpgButtonStyleStd as IpgButtonStyleStd,
    IpgContainerStyleStd as IpgContainerStyleStd,
    IpgCheckboxParam as IpgCheckboxParam,
    IpgCheckboxStyleStd as IpgCheckboxStyleStd,
    IpgCheckboxStyleParam as IpgCheckboxStyleParam,
    IpgColor as IpgColor,
    IpgColumnParam as IpgColumnParam,
    IpgContainerParam as IpgContainerParam,
    IpgContainerStyleParam as IpgContainerStyleParam,
    IpgDatePickerParam as IpgDatePickerParam,
    IpgDividerDirection as IpgDividerDirection,
    IpgDividerParam as IpgDividerParam,
    IpgDividerStyleParam as IpgDividerStyleParam,
    IpgIcon as IpgIcon,
    IpgPickListHandle as IpgPickListHandle,
    IpgRadioDirection as IpgRadioDirection,
    IpgRadioParam as IpgRadioParam,
    IpgRadioStyleParam as IpgRadioStyleParam,
    IpgRowParam as IpgRowParam,
    IpgScrollableParam as IpgScrollableParam,
    IpgScrollableStyleParam as IpgScrollableStyleParam,
    IpgScrollerParam as IpgScrollerParam,
    IpgSelectableTextParam as IpgSelectableTextParam,
    IpgSeparatorParam as IpgSeparatorParam,
    IpgSeparatorType as IpgSeparatorType,
    IpgSeparatorStyleParam as IpgSeparatorStyleParam,
    IpgSliderParam as IpgSliderParam,
    IpgSliderStyleParam as IpgSliderStyleParam,
    IpgStackParam as IpgStackParam,
    IpgStyleStandard as IpgStyleStandard,
    IpgTableParam as IpgTableParam,
    IpgTextInputParam as IpgTextInputParam,
    IpgTextParam as IpgTextParam,
    IpgTogglerParam as IpgTogglerParam,
    IpgTogglerStyleParam as IpgTogglerStyleParam,
    IpgWindowLevel as IpgWindowLevel,
    IpgWindowMode as IpgWindowMode,
    IpgWindowParam as IpgWindowParam,
    IpgWindowTheme as IpgWindowTheme,
    TextShaping as TextShaping,
    TextWrapping as TextWrapping,
    start_session as start_session,
    update_widget as update_widget,
    generate_id as generate_id,
)

# ---------------------------------------------------------------------------
# Wrapped widget functions — full signatures with parent_id made optional
# ---------------------------------------------------------------------------

def add_button(
    *,
    parent_id: Optional[str] = None,
    label: str = ...,
    gen_id: Optional[int] = None,
    on_press: Optional[Callable] = None,
    width: Optional[float] = None,
    width_fill: bool = False,
    height: Optional[float] = None,
    height_fill: bool = False,
    padding: Optional[list[float]] = None,
    text_top_left: Optional[bool] = None,
    text_top_center: Optional[bool] = None,
    text_top_right: Optional[bool] = None,
    text_center_left: Optional[bool] = None,
    text_center: bool = True,
    text_center_right: Optional[bool] = None,
    text_bottom_left: Optional[bool] = None,
    text_bottom_center: Optional[bool] = None,
    text_bottom_right: Optional[bool] = None,
    text_size: Optional[float] = None,
    clip: Optional[bool] = None,
    style_id: Optional[int] = None,
    style_standard: Optional[IpgButtonStyleStd] = None,
    style_arrow: Optional[IpgArrow] = None,
    user_data: Optional[Any] = None,
    show: bool = True,
) -> int:
    """Creates a new Button with the given content.
    Widgets need to be placed into a container type
    
    Usage::

        with Window(title="My App"):
            with Container():
                add_button(label="Press me")
                
    Parameters
    ----------
    parent_id : str, optional
        id of another container.  When omitted, uses the current context
        manager's parent_id.
    label : str, optional
        label of Button, this field is ignored when style_arrow is used.
    gen_id : int, optional
        The only allowable entry for this id is the value generated by
        ipg.generate_id().
    on_press : Callable, optional
        Sets the callback produced when the Button is pressed.
        Unless on_press is called, the Button will be disabled.
    width : float, optional
        Sets the width of the widget.
    width_fill : bool, optional
        Sets the width to fill the available space, overrides width.
    height : float, optional
        Sets the height of the widget.
    height_fill : bool, optional
        Sets the height to fill the available space, overrides height.
    padding : List[float], optional
        Sets the padding for widget.
        use [float] for all sides,
        use [float, float, float, float] for [top, right, bottom, left]
    text_size : float, Optional
        Size of the text
    clip : bool, Optional
        Whether to clip the label if width exceeded.
    style_id : int, Optional
        Id of the add_button_style.
    style_std_id : IpgButtonStyleStd, Optional
        Primary, Secondary, Success, Danger, Warning, Text, Subtle
    style_arrow : IpgArrow, Optional
        See dropdown list when IpgArrow. is typed.
    user_data : any
        Any data needed by user to be passed through as a callback.
    show : bool=True
        Shows or hides widget.

    Returns
    -------
    id : int
        Internal id of widget.
    """
    ...

# ---------------------------------------------------------------------------
# Other wrapped widget functions — TODO: add full signatures later
# ---------------------------------------------------------------------------

def add_checkbox(*, parent_id: Optional[str] = None, **kwargs: Any) -> int: ...
def add_color_picker(*, parent_id: Optional[str] = None, **kwargs: Any) -> int: ...
def add_date_picker(*, parent_id: Optional[str] = None, **kwargs: Any) -> int: ...
def add_divider(*, parent_id: Optional[str] = None, **kwargs: Any) -> int: ...
def add_pick_list(*, parent_id: Optional[str] = None, **kwargs: Any) -> int: ...
def add_radio(*, parent_id: Optional[str] = None, **kwargs: Any) -> int: ...
def add_selectable_text(*, parent_id: Optional[str] = None, **kwargs: Any) -> int: ...
def add_separator(*, parent_id: Optional[str] = None, **kwargs: Any) -> int: ...
def add_slider(*, parent_id: Optional[str] = None, **kwargs: Any) -> int: ...
def add_space(*, parent_id: Optional[str] = None, **kwargs: Any) -> int: ...
def add_text_input(*, parent_id: Optional[str] = None, **kwargs: Any) -> int: ...
def add_text(*, parent_id: Optional[str] = None, **kwargs: Any) -> int: ...
def add_toggler(*, parent_id: Optional[str] = None, **kwargs: Any) -> int: ...

# ---------------------------------------------------------------------------
# Wrapped container functions — full signatures
# ---------------------------------------------------------------------------

def add_container(
    *,
    id: Optional[str] = None,
    window_id: Optional[str] = None,
    parent_id: Optional[str] = None,
    width: Optional[float] = None,
    width_fill: bool = False,
    height: Optional[float] = None,
    height_fill: bool = False,
    clip: Optional[bool] = None,
    max_height: Optional[float] = None,
    max_width: Optional[float] = None,
    align_bottom_center: Optional[bool] = None,
    align_bottom_left: Optional[bool] = None,
    align_bottom_right: Optional[bool] = None,
    align_center_center: Optional[bool] = None,
    align_center_left: Optional[bool] = None,
    align_center_right: Optional[bool] = None,
    align_top_center: Optional[bool] = None,
    align_top_left: Optional[bool] = None,
    align_top_right: Optional[bool] = None,
    padding: Optional[list[float]] = None,
    show: bool = True,
    style_id: Optional[int] = None,
) -> int:
    """Add a container widget.

    Wraps the iced Container — a widget that aligns its contents inside
    of its boundaries.  Unlike a row or column a container can only have
    one child.

    Parameters
    ----------
        id : str, optional
            The id of the container (maps to container_id).
        window_id : str, optional
            Id of the window.  Defaults to current Window context.
        parent_id : str, optional
            Parent container id.  Defaults to current context.
        width : float, optional
            Sets the width of the Container.
        width_fill : bool
            Sets the width to fill the available space.
        height : float, optional
            Sets the height of the Container.
        height_fill : bool
            Sets the height to fill the available space.
        clip : bool, optional
            Whether to clip contents on overflow.
        max_height : float, optional
            Maximum height of the Container.
        max_width : float, optional
            Maximum width of the Container.
        align_bottom_center .. align_top_right : bool, optional
            Alignment flags for content positioning.
        padding : list[float], optional
            Padding. [float] for all sides, [top, right, bottom, left].
        show : bool
            Shows or hides the container.
        style_id : int, optional
            Id returned from add_container_style.

    Returns
    -------
    int
        Internal id of the widget.
    """
    ...

def add_column(
    *,
    id: Optional[str] = None,
    window_id: Optional[str] = None,
    parent_id: Optional[str] = None,
    align: Align = ...,
    width: Optional[float] = None,
    height: Optional[float] = None,
    width_fill: bool = False,
    height_fill: bool = False,
    max_width: float = ...,
    padding: Optional[list[float]] = None,
    spacing: float = 20.0,
    clip: bool = False,
    show: bool = True,
) -> int:
    """Add a Column container that distributes its contents vertically.

    Parameters
    ----------
        id : str, optional
            The id of the container (maps to container_id).
        window_id : str, optional
            Id of the window.  Defaults to current Window context.
        parent_id : str, optional
            Parent container id.  Defaults to current context.
        align : Align
            Vertical alignment of items; Start, Center, End.
        width : float, optional
            Sets the width.
        height : float, optional
            Sets the height.
        width_fill : bool
            Fill available width.
        height_fill : bool
            Fill available height.
        max_width : float
            Maximum width the container is allowed.
        padding : list[float], optional
            Padding. [float] for all sides, [top, right, bottom, left].
        spacing : float
            Spacing between items.
        clip : bool
            Whether to clip text if > container.
        show : bool
            Shows or hides widget.

    Returns
    -------
    int
        Internal id of the widget.
    """
    ...

def add_row(
    *,
    id: Optional[str] = None,
    window_id: Optional[str] = None,
    parent_id: Optional[str] = None,
    align: Align = ...,
    width: Optional[float] = None,
    height: Optional[float] = None,
    width_fill: bool = False,
    height_fill: bool = False,
    padding: Optional[list[float]] = None,
    spacing: float = 20.0,
    clip: bool = False,
    show: bool = True,
) -> int:
    """Add a Row container that distributes its contents horizontally.

    Parameters
    ----------
        id : str, optional
            The id of the container (maps to container_id).
        window_id : str, optional
            Id of the window.  Defaults to current Window context.
        parent_id : str, optional
            Parent container id.  Defaults to current context.
        align : Align
            Alignment; Start, Center, End.
        width : float, optional
            Sets the width.
        height : float, optional
            Sets the height.
        width_fill : bool
            Fill available width.
        height_fill : bool
            Fill available height.
        padding : list[float], optional
            Padding. [float] for all sides, [top, right, bottom, left].
        spacing : float
            Spacing between items.
        clip : bool
            Whether to clip content.
        show : bool
            Shows or hides widget.

    Returns
    -------
    int
        Internal id of the widget.
    """
    ...

def add_scrollable(
    *,
    id: Optional[str] = None,
    window_id: Optional[str] = None,
    parent_id: Optional[str] = None,
    width: Optional[float] = None,
    height: Optional[float] = None,
    width_fill: bool = False,
    height_fill: bool = False,
    direction: Any = None,
    h_bar_width: float = 10.0,
    h_bar_margin: float = 0.0,
    h_scroller_width: float = 10.0,
    h_spacing: float = 0.0,
    h_bar_alignment: Align = ...,
    v_bar_width: float = 10.0,
    v_bar_margin: float = 0.0,
    v_scroller_width: float = 10.0,
    v_spacing: float = 0.0,
    v_bar_alignment: Align = ...,
    on_scroll: Optional[Callable] = None,
    style_id: Optional[str] = None,
    user_data: Optional[Any] = None,
) -> int:
    """Add a Scrollable wrapper around a container.

    Parameters
    ----------
        id : str, optional
            The id of the scrollable (maps to container_id).
        window_id : str, optional
            Id of the window.  Defaults to current Window context.
        parent_id : str, optional
            Parent container id.  Defaults to current context.
        width : float, optional
            Sets the width.
        height : float, optional
            Sets the height.
        width_fill : bool
            Fill available width.
        height_fill : bool
            Fill available height.
        direction : IpgScrollableDirection
            Vertical, Horizontal, or Both.
        h_bar_width/h_bar_margin/h_scroller_width/h_spacing/h_bar_alignment
            Horizontal scrollbar settings.
        v_bar_width/v_bar_margin/v_scroller_width/v_spacing/v_bar_alignment
            Vertical scrollbar settings.
        on_scroll : Callable, optional
            Callback on scroll.
        style_id : str, optional
            Style id.
        user_data : any, optional
            User data passed through callbacks.

    Returns
    -------
    int
        Internal id of the widget.
    """
    ...

def add_stack(
    *,
    parent_id: Optional[str] = None,
    width: Optional[float] = None,
    height: Optional[float] = None,
    width_fill: bool = False,
    height_fill: bool = False,
    hide_index: Optional[int] = None,
    show: bool = True,
) -> int:
    """Add a Stack of containers.

    Parameters
    ----------
        parent_id : str, optional
            Parent container id.  Defaults to current context.
        width : float, optional
            Sets the width.
        height : float, optional
            Sets the height.
        width_fill : bool
            Fill available width.
        height_fill : bool
            Fill available height.
        hide_index : int, optional
            Which item index to hide.
        show : bool
            Shows or hides widget.

    Returns
    -------
    int
        Internal id of the widget.
    """
    ...

def add_table(*, parent_id: Optional[str] = None, **kwargs: Any) -> int: ...

# ---------------------------------------------------------------------------
# add_window wrapper
# ---------------------------------------------------------------------------

def add_window(
    *,
    id: Optional[str] = None,
    title: str = ...,
    width: float = ...,
    height: float = ...,
    max_width: Optional[float] = None,
    max_height: Optional[float] = None,
    min_width: Optional[float] = None,
    min_height: Optional[float] = None,
    pos_x: Optional[float] = None,
    pos_y: Optional[float] = None,
    pos_centered: bool = False,
    resizable: bool = True,
    decorations: bool = True,
    transparent: bool = False,
    level: IpgWindowLevel = ...,
    theme: IpgWindowTheme = ...,
    debug: bool = False,
    exit_on_close: bool = True,
    mode: IpgWindowMode = ...,
    gen_id: Optional[int] = None,
) -> int:
    """Add a window to the GUI.

    Parameters
    ----------
        id : str, optional
            Window id.  Auto-generated if omitted.
        title : str
            Title in the window title bar.
        width : float
            Window width.
        height : float
            Window height.
        max_width/max_height : float, optional
            Maximum window dimensions.
        min_width/min_height : float, optional
            Minimum window dimensions.
        pos_x/pos_y : float, optional
            Window position.
        pos_centered : bool
            Center the window.
        resizable : bool
            Whether the window can be resized.
        decorations : bool
            Whether to show title bar and border.
        transparent : bool
            Whether the window is transparent.
        level : IpgWindowLevel
            Normal, AlwaysOnBottom, AlwaysOnTop.
        theme : IpgWindowTheme
            Window theme.
        debug : bool
            Draw boxes around widgets to see layout.
        exit_on_close : bool
            Whether closing this window exits the app.
        mode : IpgWindowMode
            Windowed, FullScreen, Hidden.
        gen_id : int, optional
            Value from generate_id().

    Returns
    -------
    int
        Internal id of the widget.
    """
    ...

# ---------------------------------------------------------------------------
# Context managers
# ---------------------------------------------------------------------------

class Window:
    """Context manager that calls add_window and tracks the window id.

    Usage::

        with Window(title="My App", pos_centered=True) as wnd_id: (if needed)
            with Container(align_center_center=True):
                add_text(content="hello")

    Parameters
    ----------
        id : str, optional
            Window id.  Auto-generated if omitted.
        title : str
            Title in the window title bar.
        width : float
            Window width.
        height : float
            Window height.
        max_width/max_height : float, optional
            Maximum window dimensions.
        min_width/min_height : float, optional
            Minimum window dimensions.
        pos_x/pos_y : float, optional
            Window position.
        pos_centered : bool
            Center the window.
        resizable : bool
            Whether the window can be resized.
        decorations : bool
            Whether to show title bar and border.
        transparent : bool
            Whether the window is transparent.
        level : IpgWindowLevel
            Normal, AlwaysOnBottom, AlwaysOnTop.
        theme : IpgWindowTheme
            Window theme.
        debug : bool
            Draw boxes around widgets to see layout.
        exit_on_close : bool
            Whether closing this window exits the app.
        mode : IpgWindowMode
            Windowed, FullScreen, Hidden.
        gen_id : int, optional
            Value from generate_id().
    """
    def __init__(
        self,
        *,
        id: Optional[str] = None,
        title: str = ...,
        width: float = ...,
        height: float = ...,
        max_width: Optional[float] = None,
        max_height: Optional[float] = None,
        min_width: Optional[float] = None,
        min_height: Optional[float] = None,
        pos_x: Optional[float] = None,
        pos_y: Optional[float] = None,
        pos_centered: bool = False,
        resizable: bool = True,
        decorations: bool = True,
        transparent: bool = False,
        level: IpgWindowLevel = ...,
        theme: IpgWindowTheme = ...,
        debug: bool = False,
        exit_on_close: bool = True,
        mode: IpgWindowMode = ...,
        gen_id: Optional[int] = None,
    ) -> None: ...
    def __enter__(self) -> int: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: TracebackType | None) -> bool: ...

class Container:
    """Context manager wrapper around add_container.

    Wraps the iced Container — a widget that aligns its contents inside
    of its boundaries.  Unlike a row or column a container can only have
    one child.

    Usage::

        with Window(title="Demo"):
            with Container(align_center=True, width_fill=True):
                add_text(content="hello")

    Parameters
    ----------
        id : str, optional
            The id of the container.  Auto-generated if omitted.
        window_id : str, optional
            Id of the window.  Defaults to current Window context.
        parent_id : str, optional
            Parent container id.  Defaults to current context.
        width : float, optional
            Sets the width of the Container.
        width_fill : bool
            Sets the width to fill the available space.
        height : float, optional
            Sets the height of the Container.
        height_fill : bool
            Sets the height to fill the available space.
        clip : bool, optional
            Whether to clip contents on overflow.
        max_height : float, optional
            Maximum height of the Container.
        max_width : float, optional
            Maximum width of the Container.
        align_bottom_center .. align_top_right : bool, optional
            Alignment flags for content positioning.
        padding : list[float], optional
            Padding. [float] for all sides, [top, right, bottom, left].
        show : bool
            Shows or hides the container.
        style_id : int, optional
            Id returned from add_container_style.
    """
    def __init__(
        self,
        *,
        id: Optional[str] = None,
        window_id: Optional[str] = None,
        parent_id: Optional[str] = None,
        width: Optional[float] = None,
        width_fill: bool = False,
        height: Optional[float] = None,
        height_fill: bool = False,
        clip: Optional[bool] = None,
        max_height: Optional[float] = None,
        max_width: Optional[float] = None,
        align_bottom_center: Optional[bool] = None,
        align_bottom_left: Optional[bool] = None,
        align_bottom_right: Optional[bool] = None,
        align_center: Optional[bool] = None,
        align_center_left: Optional[bool] = None,
        align_center_right: Optional[bool] = None,
        align_top_center: Optional[bool] = None,
        align_top_left: Optional[bool] = None,
        align_top_right: Optional[bool] = None,
        padding: Optional[list[float]] = None,
        show: bool = True,
        style_id: Optional[int] = None,
    ) -> None: ...
    def __enter__(self) -> int: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: TracebackType | None) -> bool: ...

class Column:
    """Context manager wrapper around add_column.

    A container that distributes its contents vertically.

    Usage::

        with Window(title="Demo"):
            with Column(spacing=10.0):
                add_text(content="hello")
                add_text(content="hello")

    Parameters
    ----------
        id : str, optional
            The id of the container.  Auto-generated if omitted.
        window_id : str, optional
            Id of the window.  Defaults to current Window context.
        parent_id : str, optional
            Parent container id.  Defaults to current context.
        align : Align
            Vertical alignment of items; Start, Center, End.
        width : float, optional
            Sets the width.
        height : float, optional
            Sets the height.
        width_fill : bool
            Fill available width.
        height_fill : bool
            Fill available height.
        max_width : float
            Maximum width the container is allowed.
        padding : list[float], optional
            Padding. [float] for all sides, [top, right, bottom, left].
        spacing : float
            Spacing between items.
        clip : bool
            Whether to clip text if > container.
        show : bool
            Shows or hides widget.
    """
    def __init__(
        self,
        *,
        id: Optional[str] = None,
        window_id: Optional[str] = None,
        parent_id: Optional[str] = None,
        align: Align = ...,
        width: Optional[float] = None,
        height: Optional[float] = None,
        width_fill: bool = False,
        height_fill: bool = False,
        max_width: float = ...,
        padding: Optional[list[float]] = None,
        spacing: float = 20.0,
        clip: bool = False,
        show: bool = True,
    ) -> None: ...
    def __enter__(self) -> int: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: TracebackType | None) -> bool: ...

class Row:
    """Context manager wrapper around add_row.

    A container that distributes its contents horizontally.

    Usage::

        with Window(title="Demo"):
            with Row(spacing=10.0):
                add_text(content="hello")
                add_text(content="hello")

    Parameters
    ----------
        id : str, optional
            The id of the container.  Auto-generated if omitted.
        window_id : str, optional
            Id of the window.  Defaults to current Window context.
        parent_id : str, optional
            Parent container id.  Defaults to current context.
        align : Align
            Alignment; Start, Center, End.
        width : float, optional
            Sets the width.
        height : float, optional
            Sets the height.
        width_fill : bool
            Fill available width.
        height_fill : bool
            Fill available height.
        padding : list[float], optional
            Padding. [float] for all sides, [top, right, bottom, left].
        spacing : float
            Spacing between items.
        clip : bool
            Whether to clip content.
        show : bool
            Shows or hides widget.
    """
    def __init__(
        self,
        *,
        id: Optional[str] = None,
        window_id: Optional[str] = None,
        parent_id: Optional[str] = None,
        align: Align = ...,
        width: Optional[float] = None,
        height: Optional[float] = None,
        width_fill: bool = False,
        height_fill: bool = False,
        padding: Optional[list[float]] = None,
        spacing: float = 20.0,
        clip: bool = False,
        show: bool = True,
    ) -> None: ...
    def __enter__(self) -> int: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: TracebackType | None) -> bool: ...

class Stack:
    """Context manager wrapper around add_stack.

    A stack of containers.

    Usage::

        with Window(title="Demo"):
            with Stack():
                add_text(content="hello")

    Parameters
    ----------
        id : str, optional
            The id of the container.  Auto-generated if omitted.
        window_id : str, optional
            Id of the window.  Defaults to current Window context.
        parent_id : str, optional
            Parent container id.  Defaults to current context.
        width : float, optional
            Sets the width.
        height : float, optional
            Sets the height.
        width_fill : bool
            Fill available width.
        height_fill : bool
            Fill available height.
        hide_index : int, optional
            Which item index to hide.
        show : bool
            Shows or hides widget.
    """
    def __init__(
        self,
        *,
        id: Optional[str] = None,
        window_id: Optional[str] = None,
        parent_id: Optional[str] = None,
        width: Optional[float] = None,
        height: Optional[float] = None,
        width_fill: bool = False,
        height_fill: bool = False,
        hide_index: Optional[int] = None,
        show: bool = True,
    ) -> None: ...
    def __enter__(self) -> int: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: TracebackType | None) -> bool: ...

class Scrollable:
    """Context manager wrapper around add_scrollable.

    Usage::

        with Window(title="Demo"):
            with Scrollable(width=200.0, height=100.0):
                add_text(content="long text...")

    Parameters
    ----------
        id : str, optional
            The id of the scrollable.  Auto-generated if omitted.
        window_id : str, optional
            Id of the window.  Defaults to current Window context.
        parent_id : str, optional
            Parent container id.  Defaults to current context.
        width : float, optional
            Sets the width.
        height : float, optional
            Sets the height.
        width_fill : bool
            Fill available width.
        height_fill : bool
            Fill available height.
        direction : IpgScrollableDirection
            Vertical, Horizontal, or Both.
        h_bar_width : float
            Horizontal bar width.
        h_bar_margin : float
            Horizontal bar margin.
        h_scroller_width : float
            Horizontal scroller bar width.
        h_spacing : float
            Moves the bar down.
        h_bar_alignment : Align
            Horizontal bar alignment Start or End.
        v_bar_width : float
            Vertical bar width.
        v_bar_margin : float
            Vertical bar margin.
        v_scroller_width : float
            Vertical scroller bar width.
        v_spacing : float
            Moves the bar right.
        v_bar_alignment : Align
            Vertical bar alignment Start or End.
        on_scroll : Callable, optional
            Callback on scroll.
        style_id : str, optional
            Style id.
        user_data : any, optional
            User data passed through callbacks.
    """
    def __init__(
        self,
        *,
        id: Optional[str] = None,
        window_id: Optional[str] = None,
        parent_id: Optional[str] = None,
        width: Optional[float] = None,
        height: Optional[float] = None,
        width_fill: bool = False,
        height_fill: bool = False,
        direction: Any = None,
        h_bar_width: float = 10.0,
        h_bar_margin: float = 0.0,
        h_scroller_width: float = 10.0,
        h_spacing: float = 0.0,
        h_bar_alignment: Align = ...,
        v_bar_width: float = 10.0,
        v_bar_margin: float = 0.0,
        v_scroller_width: float = 10.0,
        v_spacing: float = 0.0,
        v_bar_alignment: Align = ...,
        on_scroll: Optional[Callable] = None,
        style_id: Optional[str] = None,
        user_data: Optional[Any] = None,
    ) -> None: ...
    def __enter__(self) -> int: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: TracebackType | None) -> bool: ...
